language: node_js
node_js:
  - "0.10"
  - "0.8"
services:
  - mongodb
before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq melt
  - sudo apt-get install -qq ffmpeg melt libmlt-dev libmlt++-dev
